version: '3.9'

services:
  filezilla:
    container_name: filezilla
    image: ghcr.io/linuxserver/filezilla
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Kuching
    volumes:
      - /data/filezilla/filezilla:/config
      - /data/filezilla/media:/data
    ports:
      - 3000:3000
    restart: always